# UsageDaily：usage 的日彙總表（04 §8.2，2A-3）。普通表＋RLS（建表後立即開，
# 內容是用量輪廓，與 usage_logs 同級敏感）。

# Generated by Django 5.2.16 on 2026-08-21 16:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


def _enable_rls(apps, schema_editor):
    from apps.platform.migrations import _rls

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(_rls.enable("platform_usagedaily"))


def _disable_rls(apps, schema_editor):
    from apps.platform.migrations import _rls

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(_rls.disable("platform_usagedaily"))


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0009_analytics_permission_seed"),
        ("platform", "0003_quotacounter"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageDaily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("day", models.DateField()),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("category", models.TextField()),
                ("model", models.TextField()),
                ("requests", models.IntegerField(default=0)),
                ("prompt_tokens", models.BigIntegerField(default=0)),
                ("completion_tokens", models.BigIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_daily",
                        to="identity.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "platform_usagedaily",
                "indexes": [
                    models.Index(fields=["tenant", "day"], name="ix_usagedaily_tenant_day")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "day", "user_id", "category", "model"),
                        name="uq_usagedaily_bucket",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.RunPython(_enable_rls, _disable_rls),
    ]
