# Generated by Django 5.2.16 on 2026-08-29 02:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0012_platform_table_grants"),
        ("platform", "0006_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantDataKey",
            fields=[
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="data_key",
                        serialize=False,
                        to="identity.tenant",
                    ),
                ),
                ("wrapped_key", models.BinaryField()),
                ("kek_version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "platform_tenantdatakey",
            },
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("ciphertext", models.BinaryField()),
                ("hint", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credentials",
                        to="identity.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "platform_credential",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "name"), name="uq_credential_tenant_name"
                    )
                ],
            },
        ),
    ]
