# Generated by Django 5.2.16 on 2026-08-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpikeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "spike_item",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-created_at"], name="ix_spike_item_tenant_ct"
                    )
                ],
            },
        ),
    ]
