# Generated by Django 5.2.16 on 2026-08-16 13:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0008_chat_permission_seed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.TextField()),
                ("name", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("active_version_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prompts",
                        to="identity.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.IntegerField()),
                ("status", models.TextField(default="draft")),
                ("template", models.TextField()),
                ("variables_schema", models.JSONField(blank=True, default=dict)),
                ("model_hint", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("published_by", models.UUIDField(blank=True, null=True)),
                ("change_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="ai.prompt",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(fields=["tenant", "key"], name="ix_prompt_tenant_key"),
        ),
        migrations.AddConstraint(
            model_name="prompt",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key"), name="uq_prompt_tenant_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="prompt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", True)),
                fields=("key",),
                name="uq_prompt_system_key",
            ),
        ),
        migrations.AddIndex(
            model_name="promptversion",
            index=models.Index(fields=["prompt", "version"], name="ix_promptversion_prompt"),
        ),
        migrations.AddConstraint(
            model_name="promptversion",
            constraint=models.UniqueConstraint(
                fields=("prompt", "version"), name="uq_promptversion_number"
            ),
        ),
    ]
