# Generated by Django 5.2.16 on 2026-08-09 12:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0005_permission_seed"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, default="")),
                ("config", models.JSONField(blank=True, default=dict)),
                ("embedding_model", models.TextField(default="")),
                ("embedding_version", models.IntegerField(default=1)),
                ("knowledge_version", models.IntegerField(default=1)),
                ("status", models.TextField(default="active")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_bases",
                        to="identity.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("filename", models.TextField()),
                ("mime_type", models.TextField()),
                ("storage_key", models.TextField()),
                ("content_hash", models.TextField()),
                ("size_bytes", models.BigIntegerField()),
                ("source_type", models.TextField(default="upload")),
                ("source_meta", models.JSONField(blank=True, default=dict)),
                ("status", models.TextField(default="uploaded")),
                ("doc_version", models.IntegerField(default=1)),
                ("error", models.JSONField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="identity.tenant",
                    ),
                ),
                (
                    "kb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="knowledge.knowledgebase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("seq", models.IntegerField()),
                ("content", models.TextField()),
                ("token_count", models.IntegerField(default=0)),
                ("chunk_version", models.IntegerField(default=1)),
                ("doc_version", models.IntegerField(default=1)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("superseded", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chunks",
                        to="identity.tenant",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chunks",
                        to="knowledge.document",
                    ),
                ),
                (
                    "kb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chunks",
                        to="knowledge.knowledgebase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EtlJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("doc_version", models.IntegerField(default=1)),
                ("stage", models.TextField()),
                ("status", models.TextField(default="pending")),
                ("attempt", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("error", models.JSONField(blank=True, null=True)),
                ("celery_task_id", models.TextField(blank=True, default="")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etl_jobs",
                        to="knowledge.document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etl_jobs",
                        to="identity.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="ix_etl_job_tenant_status")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "doc_version", "stage"),
                        name="uq_etl_job_document_version_stage",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgebase",
            index=models.Index(fields=["tenant", "status"], name="ix_kb_tenant_status"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["tenant", "kb", "status"], name="ix_doc_tenant_kb_status"),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("tenant", "kb", "content_hash"), name="uq_document_tenant_kb_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                condition=models.Q(("superseded", False)),
                fields=["tenant", "kb"],
                name="ix_chunk_tenant_kb_active",
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["tenant", "document", "seq"], name="ix_chunk_tenant_doc_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("document", "doc_version", "seq"), name="uq_chunk_document_version_seq"
            ),
        ),
    ]
