# Generated by Django 5.2.16 on 2026-08-15 14:10

import uuid

import django.db.models.deletion
import pgvector.django.halfvec
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0006_knowledge_permission_seed"),
        ("knowledge", "0002_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="Embedding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("model", models.TextField()),
                ("embedding_version", models.IntegerField(default=1)),
                ("vector", pgvector.django.halfvec.HalfVectorField(dimensions=1536)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="embeddings",
                        to="knowledge.chunk",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="embeddings",
                        to="identity.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["vector"],
                        m=16,
                        name="ix_embedding_vector_hnsw",
                        opclasses=["halfvec_cosine_ops"],
                    ),
                    models.Index(fields=["tenant", "chunk"], name="ix_embedding_tenant_chunk"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chunk", "model", "embedding_version"),
                        name="uq_embedding_chunk_model_version",
                    )
                ],
            },
        ),
    ]
