# Generated by Django 5.2.16 on 2026-08-28 13:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0012_platform_table_grants"),
        ("knowledge", "0006_chunk_fts_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="indexed_knowledge_version",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="KbReindexJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("target_model", models.TextField()),
                ("target_embedding_version", models.IntegerField()),
                ("target_knowledge_version", models.IntegerField()),
                ("rechunk", models.BooleanField(default=False)),
                ("status", models.TextField(default="pending")),
                ("total_chunks", models.IntegerField(default=0)),
                ("embedded_chunks", models.IntegerField(default=0)),
                ("total_documents", models.IntegerField(default=0)),
                ("rechunked_documents", models.IntegerField(default=0)),
                ("rechunk_cursor", models.UUIDField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("switched_at", models.DateTimeField(blank=True, null=True)),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.JSONField(blank=True, null=True)),
                (
                    "kb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reindex_jobs",
                        to="knowledge.knowledgebase",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kb_reindex_jobs",
                        to="identity.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "kb", "-created_at"], name="ix_reindex_tenant_kb_time"
                    ),
                    models.Index(fields=["tenant", "status"], name="ix_reindex_tenant_status"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "rechunking", "embedding"])),
                        fields=("kb",),
                        name="uq_reindex_job_active_per_kb",
                    )
                ],
            },
        ),
    ]
