# Generated by Django 5.2.16 on 2026-08-16 07:14
#
# **手改過**：`Message` 是分區表（05 §5.2），而 Django 不會產生
# `PARTITION BY RANGE`。見下方 `SeparateDatabaseAndState` 的註解。

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

# migration 執行當下起算，一次預建這麼多個月。
#
# 05 §5.2 原訂由 Celery Beat 月初預建下 3 個月，**但 Beat 目前不存在**（排 2A，
# 1C-3 已記過同一個缺口）。在那之前一次建 12 個月，並由
# `tests/integration/test_conversation_models.py::test_enough_future_partitions_exist`
# 在剩餘不足 3 個月時先紅——提醒出現在 CI 上，比出現在使用者的錯誤訊息上早好幾個月。
#
# **刻意不建 DEFAULT 分區**：有 default 的話，超出範圍的資料會安靜地全部擠進去，
# 而分區等於沒有作用；沒有 default 時 INSERT 直接失敗，那是看得見的。
MONTHS_AHEAD = 12


def _create_message() -> str:
    """`CREATE TABLE ... PARTITION BY RANGE (created_at)`。

    欄位順序與型別必須與上面 `state_operations` 的 CreateModel 一致。
    **PK 是 (id, created_at)**：PostgreSQL 要求分區鍵在每個唯一約束裡。
    """
    return """
        CREATE TABLE conversation_message (
            id uuid NOT NULL,
            tenant_id uuid NOT NULL REFERENCES identity_tenant(id) DEFERRABLE INITIALLY DEFERRED,
            conversation_id uuid NOT NULL
                REFERENCES conversation_conversation(id) DEFERRABLE INITIALLY DEFERRED,
            role text NOT NULL,
            content text NOT NULL DEFAULT '',
            citations jsonb NOT NULL DEFAULT '[]'::jsonb,
            tool_calls jsonb NOT NULL DEFAULT '[]'::jsonb,
            tool_results jsonb NOT NULL DEFAULT '[]'::jsonb,
            model text NOT NULL DEFAULT '',
            prompt_version integer NULL,
            usage jsonb NOT NULL DEFAULT '{}'::jsonb,
            status text NOT NULL DEFAULT 'completed',
            error jsonb NULL,
            created_at timestamptz NOT NULL,
            updated_at timestamptz NOT NULL,
            deleted_at timestamptz NULL,
            PRIMARY KEY (id, created_at)
        ) PARTITION BY RANGE (created_at);

        -- 05 §4 的兩組索引。建在父表上才會自動傳播到每一個分區（含 2A 之後新建的）。
        CREATE INDEX ix_message_conversation_created
            ON conversation_message (conversation_id, created_at);
        CREATE INDEX ix_message_tenant_created
            ON conversation_message (tenant_id, created_at);
    """


def _drop_message() -> str:
    return "DROP TABLE IF EXISTS conversation_message CASCADE;"


def _month_bounds(index: int) -> tuple[str, str, str]:
    """第 `index` 個月的分區名與上下界（以 migration 執行當月為第 0 個）。"""
    now = datetime.now(UTC)
    year, month = now.year, now.month + index
    year, month = year + (month - 1) // 12, (month - 1) % 12 + 1
    next_year, next_month = (year, month + 1) if month < 12 else (year + 1, 1)
    return (
        f"conversation_message_{year:04d}_{month:02d}",
        f"{year:04d}-{month:02d}-01",
        f"{next_year:04d}-{next_month:02d}-01",
    )


def _create_partitions(apps: Any, schema_editor: Any) -> None:
    """預建 `MONTHS_AHEAD` 個月的分區，並逐一開啟 RLS。

    **每個分區都要自己開 RLS 並建 policy**：父表的 policy 只保護「經由父表」的存取，
    子分區是獨立的表，直接查它時父表的 policy 不適用。而分區是會一直新增的東西——
    2A 的 Beat 建出新分區時若漏了這一步，會出現一個「查父表安全、查子分區不安全」
    的缺口，且完全無症狀。`tests/integration/test_rls_conversation.py` 逐一檢查。
    """
    from apps.conversation.migrations import _rls

    with schema_editor.connection.cursor() as cursor:
        for index in range(MONTHS_AHEAD):
            name, start, end = _month_bounds(index)
            cursor.execute(
                f"CREATE TABLE IF NOT EXISTS {name} PARTITION OF conversation_message "
                f"FOR VALUES FROM ('{start}') TO ('{end}');"
            )
            cursor.execute(_rls.enable(name))


def _noop(apps: Any, schema_editor: Any) -> None:
    """反向不做事：分區會隨父表的 DROP TABLE ... CASCADE 一起消失。"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0007_rag_permission_seed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.TextField(blank=True, default="")),
                (
                    "kb_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                ("model_config_id", models.UUIDField(blank=True, null=True)),
                ("prompt_key", models.TextField(blank=True, default="")),
                ("status", models.TextField(default="active")),
                ("pinned", models.BooleanField(default=False)),
                ("message_count", models.IntegerField(default=0)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to="identity.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_conversation",
            },
        ),
        migrations.CreateModel(
            name="MemorySnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("upto_message_id", models.UUIDField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, default="")),
                ("token_count", models.IntegerField(default=0)),
                ("version", models.IntegerField(default=1)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memory_snapshots",
                        to="conversation.conversation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memory_snapshots",
                        to="identity.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "conversation_memorysnapshot",
            },
        ),
        # ── Message：分區表（05 §3.4、§5.2）──────────────────────────
        #
        # **Django 不支援分區表**，因此這張表拆成兩半：`state_operations` 讓 Django 的
        # state 認得這個 model（ORM、後續 migration 的 state 推導都照常運作），而真正的
        # DDL 由 `database_operations` 自己下。兩邊的欄位必須逐一對齊——對不上的症狀是
        # ORM 查詢報「欄位不存在」，而 makemigrations 完全看不出來。
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Message",
                    fields=[
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("deleted_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("role", models.TextField()),
                        ("content", models.TextField(blank=True, default="")),
                        ("citations", models.JSONField(blank=True, default=list)),
                        ("tool_calls", models.JSONField(blank=True, default=list)),
                        ("tool_results", models.JSONField(blank=True, default=list)),
                        ("model", models.TextField(blank=True, default="")),
                        ("prompt_version", models.IntegerField(blank=True, null=True)),
                        ("usage", models.JSONField(blank=True, default=dict)),
                        ("status", models.TextField(default="completed")),
                        ("error", models.JSONField(blank=True, null=True)),
                        (
                            "conversation",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="messages",
                                to="conversation.conversation",
                            ),
                        ),
                        (
                            "tenant",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="messages",
                                to="identity.tenant",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "conversation_message",
                    },
                )
            ],
            database_operations=[
                migrations.RunSQL(sql=_create_message(), reverse_sql=_drop_message()),
                migrations.RunPython(_create_partitions, _noop),
            ],
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["tenant", "user", "-last_message_at"],
                name="ix_conv_tenant_user_recent",
            ),
        ),
        migrations.AddIndex(
            model_name="memorysnapshot",
            index=models.Index(
                fields=["tenant", "conversation", "-version"], name="ix_memory_tenant_conv_ver"
            ),
        ),
        migrations.AddConstraint(
            model_name="memorysnapshot",
            constraint=models.UniqueConstraint(
                fields=("conversation", "version"), name="uq_memory_conversation_version"
            ),
        ),
    ]
