# Generated by Django 5.2.16 on 2026-08-16 08:06

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0002_rls"),
        ("identity", "0008_chat_permission_seed"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conversation",
            name="ix_conv_tenant_user_recent",
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                models.F("tenant"),
                models.F("user"),
                models.OrderBy(
                    django.db.models.functions.comparison.Coalesce("last_message_at", "created_at"),
                    descending=True,
                ),
                condition=models.Q(("deleted_at__isnull", True)),
                name="ix_conv_tenant_user_recent",
            ),
        ),
    ]
