# Generated by Django 5.2.16 on 2026-08-08 06:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "identity_permission",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("slug", models.TextField(unique=True)),
                ("plan", models.TextField(default="free")),
                ("status", models.TextField(default="active")),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "identity_tenant",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("is_system", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles",
                        to="identity.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "identity_role",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.TextField()),
                ("password_hash", models.TextField()),
                ("display_name", models.TextField(default="")),
                ("status", models.TextField(default="active")),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="identity.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "identity_user",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user",
                        "role",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_roles",
                        to="identity.role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_roles",
                        to="identity.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_roles",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "db_table": "identity_user_role",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "role",
                        "permission",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_permissions",
                        to="identity.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_permissions",
                        to="identity.role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_permissions",
                        to="identity.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "identity_role_permission",
                "indexes": [
                    models.Index(fields=["tenant", "role"], name="ix_role_perm_tenant_role")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_role_tenant_name", nulls_distinct=False
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["tenant", "status"], name="ix_user_tenant_status"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("tenant", "email"), name="uq_user_tenant_email"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["tenant", "user"], name="ix_user_role_tenant_user"),
        ),
    ]
