# Generated by Django 5.2.16 on 2026-08-08 06:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceGrant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("principal_type", models.TextField()),
                ("principal_id", models.UUIDField()),
                ("resource_type", models.TextField()),
                ("resource_id", models.UUIDField()),
                ("access", models.TextField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_grants",
                        to="identity.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "identity_resource_grant",
                "indexes": [
                    models.Index(
                        fields=["tenant", "resource_type", "resource_id"],
                        name="ix_resource_grant_resource",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "tenant",
                            "principal_type",
                            "principal_id",
                            "resource_type",
                            "resource_id",
                        ),
                        name="uq_resource_grant",
                    )
                ],
            },
        ),
        # RLS 與建表同一個 migration：一張租戶資料表在「有 policy」之前的每一分鐘
        # 都是沒有第二道防線的，而補的時候沒人記得當初哪些查詢寫對了 filter。
        # 條件與 0002_rls.py 的形狀一致（fail closed，理由見該檔 docstring）。
        migrations.RunSQL(
            sql="""
                ALTER TABLE identity_resource_grant ENABLE ROW LEVEL SECURITY;
                ALTER TABLE identity_resource_grant FORCE ROW LEVEL SECURITY;
                CREATE POLICY tenant_isolation ON identity_resource_grant
                    USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
                    WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
            """,
            reverse_sql="""
                DROP POLICY IF EXISTS tenant_isolation ON identity_resource_grant;
                ALTER TABLE identity_resource_grant NO FORCE ROW LEVEL SECURITY;
                ALTER TABLE identity_resource_grant DISABLE ROW LEVEL SECURITY;
            """,
        ),
    ]
