# Generated by Django 5.2.16 on 2026-08-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0003_resource_grant"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantDirectory",
            fields=[
                ("tenant_id", models.UUIDField(primary_key=True, serialize=False)),
                ("slug", models.TextField(unique=True)),
                ("status", models.TextField()),
            ],
            options={
                "db_table": "identity_tenant_directory",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="token_version",
            field=models.IntegerField(default=1),
        ),
        # ── 目錄表由 trigger 維護 ───────────────────────────────────
        # 不交給應用程式：任何一條沒走 TenantService 的租戶建立（測試 factory、
        # data migration、日後的匯入腳本）都會漏掉一列，而症狀是「這個租戶就是
        # 登不進去」——查 identity_tenant 時資料明明都在，完全看不出缺的是別張表。
        #
        # 函式用 SECURITY DEFINER：寫入者是 owner（函式擁有者），與呼叫端的角色
        # 無關。目錄表沒有 RLS，所以這裡不涉及任何隔離的放寬。
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION identity_sync_tenant_directory() RETURNS trigger
                LANGUAGE plpgsql SECURITY DEFINER AS $$
                BEGIN
                    IF (TG_OP = 'DELETE') THEN
                        DELETE FROM identity_tenant_directory WHERE tenant_id = OLD.id;
                        RETURN OLD;
                    END IF;

                    INSERT INTO identity_tenant_directory (tenant_id, slug, status)
                    VALUES (NEW.id, NEW.slug, NEW.status)
                    ON CONFLICT (tenant_id) DO UPDATE
                        SET slug = EXCLUDED.slug, status = EXCLUDED.status;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER identity_tenant_directory_sync
                    AFTER INSERT OR UPDATE OR DELETE ON identity_tenant
                    FOR EACH ROW EXECUTE FUNCTION identity_sync_tenant_directory();

                -- 既有租戶補上（本 migration 之前建立的資料）
                INSERT INTO identity_tenant_directory (tenant_id, slug, status)
                SELECT id, slug, status FROM identity_tenant
                ON CONFLICT (tenant_id) DO NOTHING;
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS identity_tenant_directory_sync ON identity_tenant;
                DROP FUNCTION IF EXISTS identity_sync_tenant_directory();
            """,
        ),
        # ── 四個系統內建角色（10 §3）─────────────────────────────
        # tenant_id 為 NULL = 全租戶共用、不可修改。用 SQL 而非 ORM：data migration
        # 走 ORM 會綁在「今天的 model 長相」上，日後改欄位時舊 migration 會壞掉。
        #
        # 這裡只建角色本身，不綁 permission code：code 是隨端點一個個出現的
        # （1A-4 起），先綁等於猜。
        migrations.RunSQL(
            sql="""
                INSERT INTO identity_role (id, tenant_id, name, is_system, created_at, updated_at)
                SELECT gen_random_uuid(), NULL, name, true, now(), now()
                FROM (VALUES ('owner'), ('admin'), ('editor'), ('viewer')) AS t(name)
                ON CONFLICT DO NOTHING;
            """,
            reverse_sql="""
                DELETE FROM identity_role WHERE tenant_id IS NULL AND is_system;
            """,
        ),
    ]
